### ISSUE TITLE
Missing libraries to generate PDF

### ISSUE THREAD

**Issue by Dazeilad** [YunoHost-Apps/invoiceninja5_ynh#126]
Hi,

I just did a fresh install of InvoiceNinja (v5.6.18-C123) on the latest YNH version (v11.1.22). **I got an error on every PDF generation : "Promise was rejected with a value of ‘undefined’."**

When I looked to the storage/logs/laravel.log, it appeared that a library was missing. So I installed it, and then I had still the error, but with another library being missing, and so on... :confounded: 
So I did the process of trying and installing all the missing libraries. :sweat: 

Here is the list of what I had to install : 

- libcups2
- libdrm2
- libxkbcommon0
- libxdamage1
- libxfixes3
- libgbm1
- libpango-1.0-0
- libcairo2

Maybe you could add to the install script a test to check if these libraires are installed, or declare them as dependencies, I don't know ?

**Comment by rndmh3ro** [comment]
fixed by #128
