### ISSUE TITLE
Add proper documentation to yunohost homepage

### ISSUE THREAD

**Issue by rndmh3ro** [YunoHost-Apps/invoiceninja5_ynh#15]
### Describe the bug

There should be a proper documentation here: https://yunohost.org/en/app_invoiceninja5

Things to document aside from the usual stuff:

# api_secret usage

From https://forum.yunohost.org/t/invoice-ninja-5-ready-for-usage/18743/4:

> It was not easy to understand that there is an existing API_SECRET value (which is asked when logging in but marked as ‘optional’), and it was not easy to find it.

# "public" usage

See: 
https://forum.yunohost.org/t/server-error-trying-to-use-the-linux-snap-invoiceninja-app/19479/2

> The app was not set as “public” in the Yunohost group and permissions settings. It took me a while to realize that as I’m always logged in my Yunohost account usually. But when I tested in a isolated tab I realized I was redirected to the Yunohost login page first and understood that was probably the problem.
This is probably something interesting to state in the documentation.

**Comment by fflorent** [comment]
> ## api_secret usage

I had the same issue. Maybe worth to send email on installation with the instructions for login? (like other applications do like [PeerTube_ynh](https://github.com/YunoHost-Apps/PeerTube_ynh))

See:
 - the instruction on installation for PeerTube: https://github.com/YunoHost-Apps/peertube_ynh/blob/9bf92ff65db0dcb188834738f180dbfa34ebef09/scripts/install#L288
 - the helper source to include in the package : https://github.com/YunoHost-Apps/peertube_ynh/blob/9bf92ff65db0dcb188834738f180dbfa34ebef09/scripts/ynh_send_readme_to_admin__2

**Comment by rndmh3ro** [comment]
Good idea. Pull Requests are welcomed!

**Comment by fflorent** [comment]
In progress ;-)

**Comment by yalh76** [comment]
PR merged to master
