### ISSUE TITLE
App works but the install has issues

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/invoiceninja5_ynh#22]
### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 4.6.4.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

Using the MACOS App from Invoice Ninja. Everything works or appears to work. I did a HEALTH CHECK which is available in the app and saw the following errors:

<img width="452" alt="Screenshot 2022-07-14 at 13 30 53" src="https://user-images.githubusercontent.com/2440463/179003487-56627bd4-0319-4890-9a10-c4feefaa85e0.png">

### Expected behaviour

Permissions are wrong somewhere...
Would like to fix the queue as the app is a little sluggish

**Comment by rndmh3ro** [comment]
The queue is enabled and the file permissions are fine, because we control what is written into `.env`.
