### ISSUE TITLE
All uploaded documents (PDF files, images) are gone after update from 5.8.30 to 5.8.37

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/invoiceninja5_ynh#252]
### Describe the bug

All my previously uploaded files are gone after the update.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.10.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:
- If upgrading, current package version: *5.8.30*

### Steps to reproduce

Just update the app via webadmin interface.

### Expected behavior

My uploaded files should remain present and accessible.

### Logs
No relevant logs.

### Analysis
I think it's because of this commit: https://github.com/YunoHost-Apps/invoiceninja5_ynh/commit/8f3eba479986f5ce2ea2e052f91013c811a5b951 As invoiceninja5 stores uploaded documents in app directory those directories need to be preserved using e.g. `--keep="/public/storage"`.

After restoring to previous version fortunately all my uploaded documents are back.

**Comment by rndmh3ro** [comment]
Sorry!

I know what caused this and will revert the change.

**Comment by rndmh3ro** [comment]
I updated the version to 5.8.37~ynh2. If it is available, then it should be possible to update without losing anything.

**Comment by CodeShakingSheep** [comment]
> I updated the version to 5.8.37~ynh2. If it is available, then it should be possible to update without losing anything.

I just updated to 5.8.37~ynh2 and everything seems fine. My logo and documents are still there. Thank you for the fast fix. :pray:
