### ISSUE TITLE
Env. File no permission and "Something Went Wrong" 

### ISSUE THREAD

**Issue by flyguy729** [YunoHost-Apps/invoiceninja5_ynh#278]
### Describe the bug

Fresh Install. Open health check and it says 

env. file is not writtable by current user. 

### Context

- Hardware: 2990wx with proxmox and installed yunohost as LXC
- YunoHost 11.2.17.1 (stable).
- I have access to my server:  through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce
- Click install Invoiceninja 5 in Yunohost
- Install complete and login is fine
- Open healthcheck and see the error of env. file. 
- Open Settings > Click Invoice Design in Advance Setting ( Pro )
- Error comes up at the top " Something Went Wrong" and cant save anything.

### Expected behavior
There shouldnt be any error and i should be able to save in Advance Settings

### Logs

https://paste.yunohost.org/raw/foxarawoju

![Screenshot 2024-06-27 121647](https://github.com/YunoHost-Apps/invoiceninja5_ynh/assets/28728803/c04673af-f9c5-4741-855b-a1868b7d3308)
![Screenshot 2024-06-27 121713](https://github.com/YunoHost-Apps/invoiceninja5_ynh/assets/28728803/8880ec63-9787-4fe1-8cc7-e59a7f4f427f)

**Comment by flyguy729** [comment]
Anyone? Desperately trying to get this to work :(

**Comment by rndmh3ro** [comment]
Please provide the logs from invoice ninja. They can be found in the folder of the app in storage/logs or something like this.

**Comment by flyguy729** [comment]
> Please provide the logs from invoice ninja. They can be found in the folder of the app in storage/logs or something like this.

[lavarel.log](https://github.com/user-attachments/files/16038539/lavarel.log)

Here you go. There seems to be 2 errors

**Comment by flyguy729** [comment]
> Please provide the logs from invoice ninja. They can be found in the folder of the app in storage/logs or something like this.

sudo chown -R www-data:www-data /var/www/html
sudo find ./ -type d -exec chmod 755 {} \;
Any updates? I tried this command as well but doest work. i changed it to invoiceninja directory and it breaks invoinceninja. 

What is the " current user " of Yunohost/Invoiceninja? Perhaps if chown the correct current user , itll work? maybe www-data is no the current user?

**Comment by rndmh3ro** [comment]
I just tested this and can confirm that there's a problem when accessing the advanced settings. However this has nothing to do with the .env-file, as far as I am aware.

**Comment by rndmh3ro** [comment]
should be fixed in the latest release.

**Comment by flyguy729** [comment]
> should be fixed in the latest release.

Got it thank you for your hard work. (:
