### ISSUE TITLE
Current limitations

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/invoiceninja5_ynh#3]
Hello @rndmh3ro,

Thanks for your work !

I would like to start using Invoice Ninja this week. I read following limitations:

> This is the new version of InvoiceNinja. There are several things not working at the moment:
> 
>     migration from v4
>     installation into a sub-directory
>     sending mails

I have two questions:
- is it still true ?
- is it better to start with v4 for now and migrate from v4 to v5 when migration is working ?

I prefer to start with v5 and help fixing bugs.

**Comment by rndmh3ro** [comment]
Hi @nqb,

> is it still true ?

Yes, these are still true. Migration is probably a invoicenninja-problem - I don't know yet. Same for installation in a sub-dir.

Mail should work once I configured it appropriately.

> is it better to start with v4 for now and migrate from v4 to v5 when migration is working ?

If you just want to use it, use v4. But I'd appreciate the help in making this app better! Take a look here for some more info: https://github.com/YunoHost-Apps/invoiceninja_ynh/issues/12

**Comment by nqb** [comment]
Thanks for your feedback @rndmh3ro, I will try to use both (I have two YunoHost servers).

It looks like 4.5.30 is the one displayed on https://www.invoiceninja.org/ to download.

**Comment by rndmh3ro** [comment]
Invoiceninja5 5.1.1
invoiceninja4 4.5.32

migration still not possible for me.

**Comment by nqb** [comment]
Thanks to publish current status @rndmh3ro

**Comment by rndmh3ro** [comment]
The current limitations are now documented here: https://github.com/YunoHost-Apps/invoiceninja5_ynh/blob/master/doc/DISCLAIMER.md
