### ISSUE TITLE
Upgrade fails InvoiceNinja 5 from 5.10.21~ynh1 to 5.10.29~ynh1 

### ISSUE THREAD

**Issue by mzed2k** [YunoHost-Apps/invoiceninja5_ynh#315]
### Describe the bug

I'm trying to update InvoiceNinja 5 from `5.10.21~ynh1` to `5.10.29~ynh1` with the Yunohost Admin WebGUI.
InvoiceNinja is running fine.
Yunhost is update and restarted before update

### Context

- Hardware: VM on Proxmox
- YunoHost version: YunoHost 11.2.30.2 (stable)
- I have access to my server: Through SSH | through the webadmin | NoVNC
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: InvoiceNinja 5 from 5.10.21~ynh1 to 5.10.29~ynh1 

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade invoiceninja5
    ```

### Expected behavior

Successfull upgrade of the app

### Logs
https://paste.yunohost.org/raw/zotaruxoce

**Comment by mzed2k** [comment]
Thank you @ericgaspar.
Still not working: https://paste.yunohost.org/raw/sonuhanaqa

**Comment by mzed2k** [comment]
Thanks for your effort. Unfortunately upgrading still fails:
https://paste.yunohost.org/raw/benofobuma
Just before aborting I get this warning:
WARNING - Variable $api_secret wasn't initialized when trying to replace __API_SECRET__ in /var/www/invoiceninja5/.env

**Comment by rndmh3ro** [comment]
The changes did not land in the master branch, yet. The issue was closed by accident, sorry!

**Comment by rndmh3ro** [comment]
@mzed2k, I just tested the update to 5.10.47 and it worked for me. Can you confirm?

**Comment by mzed2k** [comment]
Thank you @rndmh3ro  well done!!
Upgrade was successful!

Info: [+++.................] > Ensuring backward compatibility...
Info: [###+++..............] > Upgrading source files...
Info: [######++++..........] > Upgrading system configurations related to invoiceninja5...
Info: [##########+++.......] > Updating configuration...
Info: [#############+++....] > Upgrading the database...
Info: [####################] > Upgrade of invoiceninja5 completed
Erfolg! invoiceninja5 aktualisiert
Erfolg! Upgrade vollständig
