### ISSUE TITLE
Invalid Secret.... But I don't have one?

### ISSUE THREAD

**Issue by baboonandsloth** [YunoHost-Apps/invoiceninja5_ynh#32]
### Describe the bug

I installed invoiceninja5 and selected my user for the admin and made a password. So I try to go to the site (ex: invoiceninja.domain.com) and then there are two optional parts of the login (2fa and secret) that I did not set, but when I try to login with the email and password from the install it says invalid secret... But I don't have one?

### Expected behavior

I assume it should log in?

**Comment by rndmh3ro** [comment]
For where to find the secret, take a look at the forums: https://forum.yunohost.org/t/invoice-ninja-5-ready-for-usage/18743/12

I just released a new version. In it is a feature that will send you an email after installation with the secret. So either reinstall invoiceninja or search for the secret like described in the forums.

Sorry about that.
