### ISSUE TITLE
IN5 v5.5.2 fails to update to existing IN5 

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/invoiceninja5_ynh#35]
### Describe the bug

Tried to upgrade to version 5.5.2

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce
Using the YNH admin interface Home/System Update

IN5 is offering to update to version 5.5.2

The installation begins. The first error is regarding PHP8.1

### Expected behavior

Once complete IN5 v5.5.2 should be available

### Logs

https://paste.yunohost.org/raw/ajusaxazir

Many thanks again

Dj

*If applicable and useful, add screenshots to help explain your problem.*

**Comment by rndmh3ro** [comment]
I don't know what the problem is so I asked in the community-forums: https://forum.yunohost.org/t/upgrade-problem-for-invoiceninja-5/21064

**Comment by yalh76** [comment]
with no reason, dependencies are removed during the install, you should retry to install it
