### ISSUE TITLE
React app redirects to /login which 404s

### ISSUE THREAD

**Issue by ndarilek** [YunoHost-Apps/invoiceninja5_ynh#74]
### Describe the bug

If I enable the React app, logging in doesn't work. Entering my credentials redirects to /login which 404s.

### Context

- Hardware: VPS
- YunoHost version: 11
- I have access to my server: All of the above
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Yes
  - If yes, please explain: Accessed the IN5 database and ran `UPDATE accounts SET set_react_as_default_ap = 1;` as per [these instructions](https://forum.invoiceninja.com/t/how-can-i-run-the-react-ui/11915/8).
- Using, or trying to install package version/branch: 5.5.41~ynh1

### Steps to reproduce

   1. Install IN5.
   2. Access the IN5 database and run `UPDATE accounts SET set_react_as_default_ap = 1;`.
   3. Visit the app in the browser. Note that the React UI now loads.
   4. Log in with any credentials.
   5. You will be redirected to /login, which 404s.

### Expected behavior

I'd like to use the React UI and redirect correctly.

**Comment by rndmh3ro** [comment]
You're probably the same nolan here and in the forums, right? :)

I posted a reply there: https://forum.invoiceninja.com/t/how-can-i-run-the-react-ui/11915/20?u=rndmh3ro

For me the following happened:

When trying to login I briefly got a error message `invalid secret`, then the 404 error appeared.

What helped for me is removing the ÀPI_SECRET` from the `.env`-file. Then the login did work.

Now what I wonder: is the `API_SECRET` still necessary if one uses 2FA?

**Comment by ndarilek** [comment]
Oh wow, totally missed that reply. Sorry.

Anyhow, I commented out API_SECRET in the .env file and restarted nginx, 
no change. Do I need to restart any php-fcgi processes somehow as well?

**Comment by ndarilek** [comment]
Update: restarted both php8.0-fpm.service and php-8.1-fpm.service, no 
change. :(

**Comment by rndmh3ro** [comment]
> Oh wow, totally missed that reply. Sorry.
 I replied liem zwo minutes ago, so no worries.

You have to clear the ninja artisan cache. In the docroot, run `php8.1 artisan config:clear` and then `php8.1 artisan config:cache`.

**Comment by ndarilek** [comment]
Oh, that worked! Thanks. Leaving this open because I'm also a bit 
unclear as to why the API secret is needed.

One quick question: do you happen to know how to remove the "undefined" 
from the app title?

**Comment by rndmh3ro** [comment]
I track the status here: #84
