### ISSUE TITLE
No login possible, after clicking on a button.

### ISSUE THREAD

**Issue by Thunderhawk2001** [YunoHost-Apps/invoiceninja5_ynh#84]
**Context**
Hardware: VPS with 6 Cores, 8 GB RAM and 320GB SSD
YunoHost version: 11.1.10 (stable)
I have access to my server: Through SSH and through the webadmin interface
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

**Describe the bug**
A colleague accidentally clicked on **this** button in Invoiceninja and now we can not log in anymore, as there is no way to enter the secret.
![image](https://user-images.githubusercontent.com/14139482/221025923-40366b88-e2c0-498a-aa80-c4823ee787f5.png)

Now the login screen looks like this:
![image](https://user-images.githubusercontent.com/14139482/221026108-804254e0-20a1-471b-8f39-c682fdda8b27.png)

We are able to work with the desktop app, but we would like to use the browser version too.

**Expected behavior**
A way to change back to the previos login screen.

**Comment by rndmh3ro** [comment]
It's the same problem as described here: https://github.com/YunoHost-Apps/invoiceninja5_ynh/issues/74

You can either:

* Access the IN5 database and run `UPDATE accounts SET set_react_as_default_ap = 1;`
or
* remove the `API_SECRET` from the `.env`-file, then run `php8.1 artisan optimize` inside the invoiceninja directory.

The reason for this is that the button changes the frontend from flutter to react. But ih the react-frontend login, there's no way to enter the `API_SECRET`.

I'm working on a fix.

**Comment by rndmh3ro** [comment]
See https://forum.yunohost.org/t/how-to-handle-settings-of-app-during-install-and-upgrade/23952

**Comment by Thunderhawk2001** [comment]
> It's the same problem as described here: #74
> 

Oh... erm...  Sorry. I must have been very, very blind to have missed that.
Sorry for wasting your time.

But thank you for providing the working solution, even after I just failed hard.

Have a great day/evening/night :)
